[build]
target = "aarch64-apple-darwin"

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = [
    "-C", "link-arg=-undefined", 
    "-C", "link-arg=dynamic_lookup"
]

[target.x86_64-apple-darwin]
linker = "clang"
rustflags = [
    "-C", "link-arg=-undefined", 
    "-C", "link-arg=dynamic_lookup"
]

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
